using System;
using UnityEngine;

namespace CatOnASkateboard.ObjectsLogicStudio
{
    /// <summary>Configures completion conditions, per-instance repetition and randomized prefab output.</summary>
    [Serializable]
    public sealed class SpawnManagementSettings
    {
        #region Fields

        [Header("Completion Conditions")]
        [Tooltip("Prefab whose instances are observed. Each instance owns separate completion counts.")]
        public GameObject SourcePrefab;
        [Tooltip("Existing interactions that must complete on the same source instance.")]
        public SpawnCondition[] Conditions = Array.Empty<SpawnCondition>();
        [Tooltip("Require every condition from the same instance. Otherwise any one completed condition triggers a draw.")]
        public bool RequireAll = true;
        [Tooltip("Allow each source instance to satisfy this rule repeatedly. Counts restart after each trigger.")]
        public bool Repeat;
        [Tooltip("Maximum successful condition cycles from each source instance, including failed probability draws.")]
        public int CyclesPerInstance = 1;
        [Header("Spawn Selection")]
        [Tooltip("Prefab choices generated by this rule. Scene objects are not accepted.")]
        public SpawnChoice[] Choices = Array.Empty<SpawnChoice>();
        [Tooltip("Choose relative weighted probability, equal probability or the authored order.")]
        public SpawnSelection Selection;
        [Tooltip("Number of prefabs drawn for each successful condition cycle.")]
        public int Draws = 1;
        [Tooltip("Do not select the same entry twice within one condition cycle.")]
        public bool WithoutReplacement;
        [Tooltip("Probability from zero to one that a completed condition cycle generates its selected prefabs.")]
        public float Chance = 1f;
        [Tooltip("Use a repeatable random stream for this rule instance.")]
        public bool FixedSeed;
        [Tooltip("Seed used when repeatable random selection is enabled.")]
        public int Seed = 1;
        [Tooltip("Optional transform animation that completes before generated objects can interact.")]
        public SpawnAnimationSettings Animation = new SpawnAnimationSettings();
        [Header("Placement And Timing")]
        [Tooltip("Minimum delay in seconds after conditions complete.")]
        public float MinimumDelay;
        [Tooltip("Maximum delay in seconds; equal values produce a fixed delay.")]
        public float MaximumDelay;
        [Tooltip("Local spawn position relative to this rule's object.")]
        public Vector3 Position;
        [Tooltip("Local Euler rotation for generated prefabs.")]
        public Vector3 Rotation;
        [Tooltip("Random horizontal displacement in metres around the output position. Zero uses the exact point.")]
        public float Radius;
        [Tooltip("Add a uniformly random rotation around the output's local up axis.")]
        public bool RandomYaw;
        [Tooltip("Limit the number of surviving objects generated by this rule at the same time.")]
        public bool LimitAlive;
        [Tooltip("Maximum surviving spawned objects. Ready cycles wait until there is room for the whole draw.")]
        public int MaximumAlive = 10;

        #endregion

        #region Methods

        #region Validation

        /// <summary>Checks references and random parameters without silently repairing authored data.</summary>
        /// <param name="warning">Receives the first actionable configuration issue.</param>
        /// <returns>True when the complete rule is usable.</returns>
        public bool TryValidate(out string warning)
        {
            // Prefab-local source references remain stable even when interaction names are changed.
            warning = string.Empty;
            if (!Prefab(SourcePrefab) || Conditions == null || Conditions.Length == 0)
                warning = "Choose a source prefab and add at least one existing interaction condition.";
            else if (Repeat && CyclesPerInstance <= 0 || Draws <= 0 || Selection is not (SpawnSelection.WeightedRandom or SpawnSelection.UniformRandom or SpawnSelection.Sequence))
                warning = "Use positive whole numbers for cycles and draws, and a supported selection mode.";
            else if (!InteractionValues.Finite(Chance) || Chance < 0f || Chance > 1f
                || !InteractionValues.Finite(MinimumDelay) || MinimumDelay < 0f
                || !InteractionValues.Finite(MaximumDelay) || MaximumDelay < MinimumDelay)
                warning = "Chance must be in [0, 1]; delays must be finite, nonnegative and ordered.";
            else if (!InteractionValues.Finite(Position) || !InteractionValues.Finite(Rotation)
                || !InteractionValues.Finite(Radius) || Radius < 0f || LimitAlive && MaximumAlive < Draws)
                warning = "Use finite placement values, a nonnegative radius, and enough live capacity for a complete draw.";
            else if (Choices == null || Choices.Length == 0)
                warning = "Add at least one output prefab.";
            if (warning.Length > 0)
                return false;

            if (Animation == null || !Animation.TryValidate(out warning))
                return false;

            // A repeated source row would ambiguously count the same completion more than once.
            for (int index = 0; index < Conditions.Length; index++)
            {
                SpawnCondition condition = Conditions[index];
                if (condition == null || condition.Source == null || !condition.Source.transform.IsChildOf(SourcePrefab.transform)
                    || condition.Count <= 0 || condition.Source is ObjectSpawnManager)
                {
                    warning = "Choose existing source interactions with positive completion quantities; spawn rules cannot trigger one another.";
                    return false;
                }
                for (int previous = 0; previous < index; previous++)
                    if (Conditions[previous].Source == condition.Source)
                    {
                        warning = "Select each source interaction only once.";
                        return false;
                    }
            }
            int eligible = 0;
            foreach (SpawnChoice choice in Choices)
            {
                if (choice == null || !Prefab(choice.Prefab) || !choice.Prefab.activeSelf
                    || !InteractionValues.Finite(choice.Weight) || choice.Weight < 0f)
                {
                    warning = "Each output needs an active prefab root and a finite nonnegative weight.";
                    return false;
                }
                if (Selection != SpawnSelection.WeightedRandom || choice.Weight > 0f)
                    eligible++;
            }
            if (eligible == 0 || WithoutReplacement && Draws > eligible)
                warning = "Provide enough eligible choices for the requested draw without replacement.";
            return warning.Length == 0;
        }

        /// <summary>Distinguishes persistent prefab roots from scene instances.</summary>
        /// <param name="prefab">Reference supplied by an editor prefab-only field.</param>
        /// <returns>True when the reference is a prefab root.</returns>
        internal static bool Prefab(GameObject prefab)
        {
            // Runtime validation needs no editor API or reflection to reject scene objects.
            return prefab != null && !prefab.scene.IsValid() && prefab.transform.parent == null;
        }

        #endregion

        #endregion
    }
}
